[2018-09-27 13:59:23] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 13:59:24] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 13:59:24] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 13:59:25] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 13:59:25] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 13:59:25] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 13:59:25] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 13:59:26] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 13:59:26] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 14:01:07] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 14:01:15] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 14:01:25] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 14:01:30] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 14:09:41] CastError: Cast to ObjectId failed for value "12313" at path "_id" for model "User"
    at new CastError (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schema\objectid.js:158:13)
    at ObjectId.SchemaType.applySetters (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:756:12)
    at ObjectId.SchemaType._castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1142:15)
    at ObjectId.SchemaType.castForQuery (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1132:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\schematype.js:1111:15)
    at cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\cast.js:295:34)
    at model.Query.Query.cast (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:3854:12)
    at model.Query.Query._castConditions (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1647:10)
    at model.Query.Query._find (C:\Users\lh\Desktop\ex_test\node_modules\mongoose\lib\query.js:1662:8)
    at process.nextTick (C:\Users\lh\Desktop\ex_test\node_modules\kareem\index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) 
[2018-09-27 14:30:26] ReferenceError: id is not defined
    at users.forEach.user (C:\Users\lh\Desktop\ex_test\modules\user\user.ctrl.js:53:26)
    at Array.forEach (<anonymous>)
    at del (C:\Users\lh\Desktop\ex_test\modules\user\user.ctrl.js:51:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) 
[2018-09-27 15:11:42] TypeError: meta.save is not a function
    at update (C:\Users\lh\Desktop\ex_test\modules\meta\meta.ctrl.js:50:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) 
[2018-09-27 17:32:46] ReferenceError: initAcl is not defined
    at update (C:\Users\lh\Desktop\ex_test\modules\user\user.ctrl.js:54:4)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) 
[2018-09-27 17:34:02] TypeError: result.toObject is not a function
    at update (C:\Users\lh\Desktop\ex_test\modules\user\user.ctrl.js:56:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) 
[2018-09-27 17:34:41] TypeError: result.toObject is not a function
    at update (C:\Users\lh\Desktop\ex_test\modules\user\user.ctrl.js:56:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) 
[2018-09-27 17:36:26] TypeError: result.toObject is not a function
    at update (C:\Users\lh\Desktop\ex_test\modules\user\user.ctrl.js:56:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) 
